ivy: fix multi-frame variable lookup bug
robpike/ivy pull request #81
Opened 2021-12-22 20:39 UTC by rsc

If g is calling f, f should never read or write g's variables.
But that's what Lookup was doing: reading g's variables
instead of globals of the same name. Assignment was correct.
This change factors out the lookup to share it between both.

2021-12-22 21:02 UTC, robpike requested changes

2021-12-22 21:02 UTC, robpike commented on exec/context.go
> +// varFrame returns the frame number for the given variable.
s/frame number/stack frame/

2021-12-22 21:22 UTC, rsc commented on exec/context.go
> +// varFrame returns the frame number for the given variable.
Done.

2021-12-22 21:22 UTC, rsc commented
Fixed comment.

2021-12-23 00:46 UTC, robpike approved these changes

2021-12-23 00:46 UTC, robpike commented
Good catch.

2021-12-23 00:46 UTC, merged