ivy: use parallel execution when possible
robpike/ivy pull request #84
Opened 2022-01-07 00:17 UTC by rsc

At least for built-in functions, element-wise or row-wise
operations can safely run each element/row in parallel.
This lets Ivy use all of a computer instead of 1 core.

On my 8-physical, 16-logical core MacBook Pro:

```
% echo '+/+/+/2*(500 500 500 rho 1)*(iota 500)' | time ./ivy.old
62625000000

       35.34 real        45.45 user         6.66 sys
% echo '+/+/+/2*(500 500 500 rho 1)*(iota 500)' | time ./ivy.new
62625000000

        8.27 real        84.08 user         8.75 sys
%
```

I don't believe the doubled user time is real.
It is counting logical-core-user-time, and the two logical cores
are both running and are therefore running at half speed.
That is, using the 16 cores is mostly the same as:

```
% echo '+/+/+/2*(500 500 500 rho 1)*(iota 500)' |  GOMAXPROCS=8 time ./ivy.new
62625000000

        8.27 real        44.89 user         5.00 sys
%
```

except of course for the bad accounting.

Passes 'go test -race' but only in Go dev branch
(needs CL 375935 fixing math/big).

2022-01-07 00:31 UTC, rsc commented
I should add that I think it's possible to identify user-defined functions that parallelize too, but I thought I'd start with the simple cases (builtins), which already a significant win.

2022-01-07 02:53 UTC, robpike requested changes
i'd never worried first and foremost about efficiency in ivy, clearly, but this is pretty - and effective when things get big.

just one trivial change please, mostly for clarity.

2022-01-07 02:53 UTC, robpike commented on value/eval.go
> +	p := runtime.GOMAXPROCS(-1)
put if ok around this block

2022-01-08 05:28 UTC, rsc commented on value/eval.go
> +	p := runtime.GOMAXPROCS(-1)
Done.

2022-01-08 05:28 UTC, rsc commented
Made requested changes; still don't know how to tell GitHub that.

2022-01-08 07:57 UTC, robpike commented on value/eval.go
> +		if p == 1 || n <= 1 || n*size < pforMinWork*3/2 {
just curious: why the 3/2?

2022-01-08 07:58 UTC, robpike approved these changes

2022-01-08 07:58 UTC, merged

2022-01-08 13:23 UTC, rsc commented
Probably it should be < MinWork*2, since that is the condition that is going to result in a single goroutine running. Not sure why I did 3/2.

2022-01-08 21:34 UTC, robpike commented
OK, I put it back to 2.