ivy: add x[i;j;k] indexing syntax, including vector-indexed assignment
robpike/ivy pull request #86
Opened 2022-01-08 05:23 UTC by rsc

This PR has two commits. 

The first changes multidimensional indexing syntax from x[i][j][k] to x[i; j; k].
Evaluating the old syntax works the same as before;
the new syntax is more efficient, because it doesn't
make temporary copies of x[i] and x[i][j].
Assigning to the old syntax is now an error,
but the error message shows the new syntax.

The second rewrites indexing to fully support
vectors and matrices as indexes, including in assignments.

See the individual commit messages for details.

2022-01-08 05:27 UTC, robpike requested changes
What happens if I do

a[1 2; 3 4] ?

Also doc.go needs fixing.

But this looks good overall; haven't done a full review yet.

2022-01-08 05:28 UTC, robpike commented
P.S. After updating doc.go, run
go generate ./...
to generate the help files

2022-01-08 19:49 UTC, rsc commented
Will take a look at doc.go.

```
% git change 86
git-codereview: changed to PR 86.
	ivy: implement multidimensional vector-indexed assignment
% go build
% ./ivy
a = 4 4 rho iota 16

a
 1  2  3  4
 5  6  7  8
 9 10 11 12
13 14 15 16

a[1 2; 3 4]
3 4
7 8

a[1 2][3 4]
index a[1 2][(3)] out of range for shape (2 4)

a[1 2; 3 4 5]
index a[_; (5)] out of range for shape (4 4)

```

The ( ) were not intentional - Int.String must be adding them? - but I kind of like them.

2022-01-08 19:58 UTC, rsc commented
Updated doc.go, added a line to demo.

2022-01-09 00:35 UTC, robpike requested changes

2022-01-09 00:35 UTC, robpike commented on value/eval.go
> +// For example, if u is a vector and v holds a single a vector,
typo

2022-01-09 00:58 UTC, robpike approved these changes

2022-01-09 00:59 UTC, merged

2022-01-09 00:59 UTC, robpike commented
I'll fix the one tweak in the other.